- name: Install Keploy CLI
  run: |
    curl --silent -L https://keploy.io/ent/install.sh | bash

- name: Run Keploy Test Suite
  run: |
   export KEPLOY_API_KEY=mADN7lUmyXLuyX4Huw== && keploy test-suite --app=6ed82155-be53-4588-8776-a8f8f9d52017 --base-path http://localhost:5000/api --cloud
