name: Run Keploy Test Suite

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Start server in background
        run: |
          npm run start &
          sleep 10 # wait for server to start
        working-directory: backend

      - name: Install Keploy CLI
        run: curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=mADN7lUmyXLuyX4Huw== && \
          keploy test-suite --app=6ed82155-be53-4588-8776-a8f8f9d52017 --base-path http://localhost:5000/api --cloud
