name: Keploy API Testing

on:
  push:
    branches: [main]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Set environment variables
        run: |
          echo "PORT=5000" >> $GITHUB_ENV
          echo "MONGO_URI=mongodb://localhost:27017/keploy-pets" >> $GITHUB_ENV

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Install jq (for extracting pet ID)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install Keploy CLI and prepare path
        run: |
          curl -s https://keploy.io/install.sh | bash
          echo "$HOME/.keploy/bin" >> $GITHUB_PATH
          ls -la $HOME/.keploy/bin  # Debug check

      - name: Start backend, call endpoints, and run Keploy tests
        run: |
          cd backend
          nohup npm start &
          sleep 10

          curl -X POST http://localhost:5000/api/pets \
            -H "Content-Type: application/json" \
            -d '{
              "name": "Tommy",
              "age": 2,
              "breed": "Labrador",
              "description": "Friendly and playful",
              "image": "https://example.com/dog.jpg"
            }' -o response.json

          curl http://localhost:5000/api/pets

          PET_ID=$(jq -r '.[0]._id' response.json || echo "")
          echo "Extracted Pet ID: $PET_ID"

          if [ "$PET_ID" != "" ]; then
            curl -X PUT http://localhost:5000/api/pets/$PET_ID \
              -H "Content-Type: application/json" \
              -d '{"description":"Updated via Keploy CI"}'

            curl -X DELETE http://localhost:5000/api/pets/$PET_ID
          fi

          $HOME/.keploy/bin/keploy test --command "npm start"
